[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
num = "0.4"
rand = { version = "0.6.1", features = ["wasm-bindgen"] }
